-- Run this in SQL Server
IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('VIDA_APP_CLIENTES') AND name='Contrasena')
  ALTER TABLE VIDA_APP_CLIENTES ADD Contrasena NVARCHAR(200) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('VIDA_APP_CLIENTES') AND name='GoogleId')
  ALTER TABLE VIDA_APP_CLIENTES ADD GoogleId NVARCHAR(200) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('VIDA_APP_CLIENTES') AND name='EmailConfirmado')
  ALTER TABLE VIDA_APP_CLIENTES ADD EmailConfirmado BIT NOT NULL DEFAULT 0;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('VIDA_APP_CLIENTES') AND name='TokenConfirmacion')
  ALTER TABLE VIDA_APP_CLIENTES ADD TokenConfirmacion NVARCHAR(100) NULL;

IF NOT EXISTS (SELECT 1 FROM sys.columns WHERE object_id=OBJECT_ID('VIDA_APP_CLIENTES') AND name='TokenExpira')
  ALTER TABLE VIDA_APP_CLIENTES ADD TokenExpira DATETIME NULL;
