-- SQL Server; después de 37,38,39. No inventa equivalencias históricas.
IF OBJECT_ID('VIDA_FINANZAS_MONEDA','U') IS NULL
 CREATE TABLE VIDA_FINANZAS_MONEDA (
 idBranch BIGINT NOT NULL, idCuenta BIGINT NOT NULL, Modo VARCHAR(5) NOT NULL DEFAULT 'USD',
 CONSTRAINT PK_FINANZAS_MONEDA PRIMARY KEY(idBranch,idCuenta),
 CONSTRAINT CK_FINANZAS_MODO CHECK(Modo IN ('USD','VES','AMBAS')));
GO
IF OBJECT_ID('VIDA_TASAS_CAMBIO','U') IS NULL
 CREATE TABLE VIDA_TASAS_CAMBIO (
 idTasa BIGINT IDENTITY PRIMARY KEY, idBranch BIGINT NOT NULL, idCuenta BIGINT NOT NULL,
 VESporUSD DECIMAL(18,8) NOT NULL CHECK(VESporUSD>0), FechaValor DATE NOT NULL,
 Fuente NVARCHAR(200) NOT NULL, UsuAlta BIGINT NOT NULL, FechaAlta DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME());
GO
IF COL_LENGTH('VIDA_CUENTAS_ABONOS','MonedaOriginal') IS NULL
 ALTER TABLE VIDA_CUENTAS_ABONOS ADD MonedaOriginal VARCHAR(3) NULL, MontoOriginal DECIMAL(18,4) NULL,
 MontoVES DECIMAL(18,4) NULL, TasaVESporUSD DECIMAL(18,8) NULL, idTasa BIGINT NULL,
 ReversoDe BIGINT NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('VIDA_CUENTAS_ABONOS') AND name='UX_ABONO_REVERSO')
 CREATE UNIQUE INDEX UX_ABONO_REVERSO ON VIDA_CUENTAS_ABONOS(idBranch,idCuenta,idDocumento,ReversoDe) WHERE ReversoDe IS NOT NULL;
GO
