-- SQL Server. Requiere 40. No modifica tasas/importes históricos.
IF COL_LENGTH('VIDA_FINANZAS_MONEDA','FuenteTasa') IS NULL
 ALTER TABLE VIDA_FINANZAS_MONEDA ADD FuenteTasa VARCHAR(12) NOT NULL
 CONSTRAINT DF_FINANZAS_FUENTE DEFAULT 'BCV_TODAY' WITH VALUES;
GO
IF COL_LENGTH('VIDA_TASAS_CAMBIO','Origen') IS NULL
 ALTER TABLE VIDA_TASAS_CAMBIO ADD Origen VARCHAR(12) NOT NULL
 CONSTRAINT DF_TASAS_ORIGEN DEFAULT 'MANUAL' WITH VALUES;
GO
IF COL_LENGTH('VIDA_TASAS_CAMBIO','PublicadaEn') IS NULL
 ALTER TABLE VIDA_TASAS_CAMBIO ADD PublicadaEn DATETIME2 NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE object_id=OBJECT_ID('VIDA_TASAS_CAMBIO') AND name='UX_TASA_API_SNAPSHOT')
 CREATE UNIQUE INDEX UX_TASA_API_SNAPSHOT ON VIDA_TASAS_CAMBIO
 (idBranch,idCuenta,FechaValor,VESporUSD,PublicadaEn) WHERE Origen='BCV_TODAY';
GO
