-- Requiere 40/41. Aplicar antes del backend/front nuevos.
IF OBJECT_ID('VIDA_POS_COTIZACIONES','U') IS NULL
 CREATE TABLE VIDA_POS_COTIZACIONES (
 idCotizacion UNIQUEIDENTIFIER NOT NULL PRIMARY KEY,
 idBranch BIGINT NOT NULL,idCuenta BIGINT NOT NULL,idUsuario BIGINT NOT NULL,idPuntoVenta BIGINT NOT NULL,
 idTasa BIGINT NOT NULL,Modo VARCHAR(5) NOT NULL,
 EmitidaEn DATETIME2 NOT NULL,ExpiraEn DATETIME2 NOT NULL);
GO
IF OBJECT_ID('VIDA_POS_MONEDA_VERSION','U') IS NULL
 CREATE TABLE VIDA_POS_MONEDA_VERSION (id INT PRIMARY KEY CHECK(id=1),FechaInicio DATETIME2 NOT NULL);
IF NOT EXISTS(SELECT 1 FROM VIDA_POS_MONEDA_VERSION WHERE id=1)
 INSERT INTO VIDA_POS_MONEDA_VERSION VALUES(1,SYSUTCDATETIME());
GO
IF COL_LENGTH('VIDA_PEDIDOS','PagoMonedaJSON') IS NULL
 ALTER TABLE VIDA_PEDIDOS ADD PagoMonedaJSON NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('VIDA_CUENTAS','TasaEmisionJSON') IS NULL
 ALTER TABLE VIDA_CUENTAS ADD TasaEmisionJSON NVARCHAR(MAX) NULL;
GO
