-- Liquidación física de repartidores por moneda. Requiere sql/42.
IF COL_LENGTH('VIDA_REPARTIDORES','SaldoPendienteVES') IS NULL
  ALTER TABLE VIDA_REPARTIDORES ADD SaldoPendienteVES DECIMAL(18,4) NOT NULL CONSTRAINT DF_REP_SALDO_VES DEFAULT(0);
GO
IF COL_LENGTH('VIDA_PEDIDOS','LiquidacionRepartidorJSON') IS NULL
  ALTER TABLE VIDA_PEDIDOS ADD LiquidacionRepartidorJSON NVARCHAR(MAX) NULL;
GO
IF COL_LENGTH('VIDA_PEDIDOS','idLiquidacionRepartidor') IS NULL
  ALTER TABLE VIDA_PEDIDOS ADD idLiquidacionRepartidor BIGINT NULL;
GO
IF COL_LENGTH('VIDA_REPARTIDOR_LIQUIDACIONES','DesgloseMonedasJSON') IS NULL
  ALTER TABLE VIDA_REPARTIDOR_LIQUIDACIONES ADD DesgloseMonedasJSON NVARCHAR(MAX) NULL;
GO
IF NOT EXISTS (SELECT 1 FROM sys.indexes WHERE name='IX_PEDIDOS_LIQ_REPARTIDOR' AND object_id=OBJECT_ID('VIDA_PEDIDOS'))
  CREATE INDEX IX_PEDIDOS_LIQ_REPARTIDOR ON VIDA_PEDIDOS(idBranch,idCuenta,idRepartidor,idLiquidacionRepartidor,Status);
GO
